### ISSUE TITLE
Missing strings and localization issues

### ISSUE THREAD

**Issue by Satton2** [TTT-2/TTTC#21]
1) 
![image](https://user-images.githubusercontent.com/23385240/95025238-f0351500-0690-11eb-8bfb-5add5e715127.png)
2) 
![image](https://user-images.githubusercontent.com/23385240/95025363-db0cb600-0691-11eb-9b7b-a9a8ac67399d.png)
3) 
![image](https://user-images.githubusercontent.com/23385240/95025255-0ba02000-0691-11eb-9e80-c7320a56b044.png)
4) 
![image](https://user-images.githubusercontent.com/23385240/95025283-39856480-0691-11eb-9ca8-2d4483702be8.png)
5) Lack of space here (_issue related to TTT2 itself?_):
![image](https://user-images.githubusercontent.com/23385240/95025352-b57fac80-0691-11eb-9055-2fe16b78e9b2.png)
![image](https://user-images.githubusercontent.com/23385240/95025336-9aad3800-0691-11eb-96cd-9b1c2cad0bfc.png)

Sadly, I cannot check everything else related to the addon's translation since there are no default classes (and I am not the guy that can create them :D), but maybe I will ask someone on TTT2 Discord to do them for that reason.

**Comment by TimGoll** [comment]
1. thanks
2. is adressed in the upcoming vgui rework
3. should the console really be localized?
4. thanks
5. alreaxdy adressed in the upcoming vgui rework

**Comment by Satton2** [comment]
> 3. should the console really be localized?

In my opinion, yes. It's also printed in chat.

**Comment by TimGoll** [comment]
added number 2
